"use strict";
(() => {
 const el=id=>document.getElementById(id), t=(es,en)=>LabI18n.language==='en'?en:es;
 const views=['demo','agents','mcp','connection','method','evidence'];let templates=[],custom=[],saving=false,profiles=[];
 const notices={};
 const notice=(id,es,en)=>{notices[id]=[es,en];el(id).textContent=t(es,en);};
 const modeNames={plan:['Planificar','Plan'],research:['Investigar','Research'],implementation:['Implementar','Implement'],review:['Revisar','Review']};
 const download=(value,name)=>{const url=URL.createObjectURL(new Blob([value],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);};
 function route(focus=false){const hash=location.hash.slice(1),view=['chat','session'].includes(hash)?'demo':views.includes(hash)?hash:'demo';document.body.classList.toggle('session-view',view==='demo');document.querySelectorAll('[data-panel]').forEach(n=>n.hidden=n.dataset.panel!==view);document.querySelectorAll('[data-view]').forEach(n=>{if(n.dataset.view===view)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});if(['workspace','trace'].includes(hash))el('examplePanel').open=true;if(focus){const heading=el('view-'+view).querySelector('h1');heading.tabIndex=-1;heading.focus();}}
 addEventListener('hashchange',()=>{route(true);if(matchMedia('(max-width: 800px)').matches){collapsed=true;sidebar();}});route();
 let collapsed=matchMedia('(max-width: 800px)').matches;try{const saved=localStorage.getItem('lab.sidebar');if(saved!==null&&!matchMedia('(max-width: 800px)').matches)collapsed=saved==='collapsed';}catch{}
 function sidebar(){el('navBackdrop').hidden=collapsed||!matchMedia('(max-width: 800px)').matches;document.body.classList.toggle('sidebar-collapsed',collapsed);el('toggleSidebar').setAttribute('aria-expanded',String(!collapsed));el('toggleSidebar').setAttribute('aria-label',collapsed?t('Expandir menú','Expand menu'):t('Contraer menú','Collapse menu'));}
 el('toggleSidebar').onclick=()=>{collapsed=!collapsed;try{localStorage.setItem('lab.sidebar',collapsed?'collapsed':'expanded');}catch{}sidebar();};el('navBackdrop').onclick=()=>{collapsed=true;sidebar();};sidebar();
 function buildData(){return {id:el('builderId').value,name:el('builderName').value.trim(),role:el('builderRole').value.trim(),prompt:el('builderPrompt').value.trim(),work_mode:el('builderMode').value};}
 function fill(row){el('builderId').value=row.id||'';el('builderName').value=row.name;el('builderRole').value=row.role;el('builderPrompt').value=row.prompt;el('builderMode').value=row.work_mode;el('builderName').focus();}
 function blank(){fill({name:'',role:'',prompt:'',work_mode:'plan'});notice('builderStatus','Nuevo agente: define el rol y sus instrucciones.','New agent: define the role and instructions.');}
 function renderAgents(){
  const selected=el('chatAgent').value,lang=LabI18n.language;el('chatAgent').replaceChildren(new Option(t('Sin rol específico','No specific role'),''));
  for(const x of templates)el('chatAgent').append(new Option(x.name[lang],x.id));for(const x of custom)el('chatAgent').append(new Option(x.name,x.id));if([...el('chatAgent').options].some(o=>o.value===selected))el('chatAgent').value=selected;
  el('templateCards').replaceChildren();for(const [index,x] of templates.entries()){
   const card=document.createElement('article');card.className='panel template-card';const title=document.createElement('h2');title.textContent=x.name[lang];const p=document.createElement('p');p.textContent=x.mission[lang];const b=document.createElement('button');b.textContent=t('Usar plantilla','Use template');b.onclick=()=>{fill({name:x.name[lang],role:x.mission[lang],prompt:x.obligations[lang].join('\n')+'\n'+t('Entrega una propuesta clara y señala lo que falta verificar.','Deliver a clear proposal and identify what still needs verification.'),work_mode:['plan','research','implementation','review'][index]});notice('builderStatus','Plantilla cargada. Adáptala y guarda tu agente.','Template loaded. Adapt it and save your agent.');};card.append(title,p,b);el('templateCards').append(card);
  }
  el('savedAgents').replaceChildren();if(!custom.length){const p=document.createElement('p');p.className='empty-state';p.textContent=t('Tu primer agente empieza con un buen encargo. Crea uno a la izquierda.','Your first agent starts with a clear assignment. Create one on the left.');el('savedAgents').append(p);}
  for(const x of custom){const card=document.createElement('article');card.className='saved-card';const h=document.createElement('h3');h.textContent=x.name;const p=document.createElement('p');p.textContent=x.role;const mode=document.createElement('small');mode.textContent=t(...modeNames[x.work_mode]);const edit=document.createElement('button');edit.textContent=t('Editar','Edit');edit.onclick=()=>fill(x);const use=document.createElement('button');use.textContent=t('Conversar','Chat');use.onclick=()=>{if(window.LabCloud?.status().busy)return;el('chatAgent').value=x.id;el('chatAgent').dispatchEvent(new Event('change'));location.hash='session';};card.append(h,p,mode,edit,use);el('savedAgents').append(card);}
 }
 async function loadAgents(){const [a,b]=await Promise.all([fetch('/api/agents'),fetch('/api/custom-agents')]);if(!a.ok||!b.ok)throw Error();templates=await a.json();custom=await b.json();renderAgents();}
 el('builderForm').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;el('saveAgent').disabled=true;try{const response=await fetch('/api/custom-agents/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(buildData())});const row=await response.json();if(!response.ok)throw {code:row.error};el('builderId').value=row.id;await loadAgents();notice('builderStatus','Agente guardado en el proyecto. Ya puedes elegirlo en Sesión.','Agent saved in the project. You can select it in Session.');}catch(e){notice('builderStatus','No se guardó el agente. Revisa los campos y evita credenciales. '+(e.code||''),'Agent was not saved. Check fields and avoid credentials. '+(e.code||''));}finally{saving=false;el('saveAgent').disabled=false;}};
 el('newAgent').onclick=blank;
 el('exportAgent').onclick=()=>{if(!el('builderForm').reportValidity())return;const row=buildData();if(/sk-[A-Za-z0-9_-]{20,}|-----BEGIN [A-Z ]*PRIVATE KEY-----/.test(JSON.stringify(row))){notice('builderStatus','Retira las credenciales antes de exportar.','Remove credentials before exporting.');return;}download(JSON.stringify({schema:1,...row,capabilities:['text_only'],hooks:['input_validation','text_only_scope','bounded_output']},null,2),'agent-definition.json');};
 const safeProfile=p=>{
  if(!p||typeof p.name!=='string'||!/^[A-Za-z0-9_-]{1,60}$/.test(p.name)||!['http','stdio'].includes(p.type))throw Error();
  if(p.type==='http'){const url=new URL(p.url);if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.search||url.hash||p.url.length>500)throw Error();return {name:p.name,type:p.type,url:p.url};}
  if(typeof p.command!=='string'||!p.command.trim()||p.command.length>150||!Array.isArray(p.args)||p.args.length>20||p.args.some(x=>typeof x!=='string'||x.length>300))throw Error();
  if(/sk-[A-Za-z0-9_-]{20,}|(?:api[-_]?key|token|password|secret)(?:=|\s)/i.test(JSON.stringify(p)))throw Error();return {name:p.name,type:p.type,command:p.command,args:p.args};
 };
 try{const rows=JSON.parse(localStorage.getItem('lab.mcp-profiles')||'[]');if(Array.isArray(rows)&&rows.length<=20)profiles=rows.map(safeProfile);}catch{profiles=[];}
 function config(){const servers=Object.create(null);for(const p of profiles)servers[p.name]=p.type==='http'?{url:p.url}:{command:p.command,args:p.args};return {mcpServers:servers};}
 function renderProfiles(){el('mcpProfiles').replaceChildren();if(!profiles.length){const p=document.createElement('p');p.textContent=t('Todavía no hay configuraciones.','No configurations yet.');el('mcpProfiles').append(p);}for(const p of profiles){const c=document.createElement('article');c.className='saved-card';const h=document.createElement('h3');h.textContent=p.name;const small=document.createElement('p');small.textContent=p.type.toUpperCase()+' · '+t('Preparada; sin conectar','Prepared; not connected');c.append(h,small);el('mcpProfiles').append(c);}el('mcpConfigPreview').textContent=JSON.stringify(config(),null,2);el('exportMcpConfig').disabled=!profiles.length;}
 function transport(){const local=el('mcpTransport').value==='stdio';el('stdioFields').hidden=!local;el('httpFields').hidden=local;el('mcpUrl').required=!local;el('mcpCommand').required=local;}
 el('mcpTransport').onchange=transport;
 for(const [id,type] of [['guideHttp','http'],['guideStdio','stdio']])el(id).onclick=()=>{el('mcpTransport').value=type;transport();el('mcpProfileName').focus();};
 el('openContext7').onclick=()=>{el('context7Details').open=true;el('mcpKey').focus();};
 el('mcpGuideForm').onsubmit=e=>{e.preventDefault();try{const p=safeProfile({name:el('mcpProfileName').value.trim(),type:el('mcpTransport').value,url:el('mcpUrl').value.trim(),command:el('mcpCommand').value.trim(),args:el('mcpTransport').value==='stdio'?JSON.parse(el('mcpArgs').value):[]});const index=profiles.findIndex(x=>x.name===p.name);if(index<0){if(profiles.length>=20)throw Error();profiles.push(p);}else profiles[index]=p;try{localStorage.setItem('lab.mcp-profiles',JSON.stringify(profiles));notice('mcpGuideStatus','Configuración guardada en este navegador. No se inició una conexión.','Configuration saved in this browser. No connection was started.');}catch{notice('mcpGuideStatus','Preparada en esta pestaña. Descárgala: el navegador no permite guardarla.','Prepared in this tab. Download it: browser storage is unavailable.');}renderProfiles();}catch{notice('mcpGuideStatus','Revisa nombre, URL sin credenciales ni parámetros, o argumentos JSON. Máximo 20 configuraciones.','Check name, URL without credentials or parameters, or JSON arguments. Maximum 20 configurations.');}};
 el('exportMcpConfig').onclick=()=>download(JSON.stringify(config(),null,2),'mcp-config.json');
 addEventListener('languagechange',()=>{sidebar();renderAgents();renderProfiles();for(const[id,pair]of Object.entries(notices))el(id).textContent=t(...pair);});
 loadAgents().catch(()=>notice('builderStatus','No se pudieron cargar los agentes. Revisa el servidor.','Agents could not be loaded. Check the server.'));transport();renderProfiles();
})();
